out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+VGNMaskEncoder+LapPE+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_VGNMaskEncoder:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 1
  model: DeepSet
  dim_pe: 8
  layers: 2
  raw_norm_type: none
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 1
  model: DeepSet
  dim_pe: 8
  layers: 2
  raw_norm_type: none
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 24
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  ckpt_period: 100
model:
  type: VGNModel_v2
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: san_graph
  scaling : 3
  layers_pre_mp: 0
  layers_mp: 15
  layers_post_mp: 3
  dim_inner: 128
  batchnorm: True
  residual: True
  num_clusters: 15
  train_eps: True
  act: relu
  dropout: 0.0
  agg: sum
  normalize_adj: False
optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.0005
  max_epoch: 1000
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5